---
title: "&#x26BD; VM-tuppekunkurranse – Tippelapper &#127942;"
author: "Helge & KI"
format:
  html:
    toc: true
    number-sections: true
    mainfont: "Arial"
execute:
  echo: false
  warning: false
  message: false
---


Her er link tilbake til rapporten:
<a href="index.html">Hovedside</a>



```{r dataprep}
source(here::here("data/datavask.R"))
```

```{r tippelapper}
spmtab <- tibble(spm="Klubblaget ditt",
                   tekst="",
                   poeng=NA) |> 
  bind_rows(alle_spm |> 
              distinct())
# |> 
  # flextable::flextable() |> 
  # flextable::set_table_properties(layout = "autofit")

svartab <- bind_rows(alle_svar|> 
            filter(id!="Fasit") ,
          metadata |> 
            filter(autograf!="Fasit") |> 
            select(id, svar = klubblaget_ditt) |> 
            mutate(spm = "Klubblaget ditt")) |> 
  left_join(metadata |> select(autograf,id), by = join_by(id)) |> 
  select(-id) |> 
pivot_wider(names_from=autograf, values_from=svar) 
# |>
  # flextable::flextable() |> 
  # flextable::set_table_properties(layout = "autofit")

spmtab |> left_join(svartab) |>
  mutate(spm = paste(spm,tekst)) |> 
  select(-tekst,-`Fasit 18.06.2026`,-`Fasit 24.06.2026`) |> 
  rename(Spørsmål = spm) |> 
  # arrange(spm) |> 
  flextable::flextable() |>
  flextable::set_table_properties(layout = "autofit") |> 
  flextable::font(fontname="Arial",part="all") |>
  flextable::bg(bg = "white", part = "header") |>
  flextable::bg(bg = "white", j = 1) |>
  flextable::set_table_properties(opts_html = list(
    scroll = list(
      height = "500px",
      freeze_first_column = TRUE
    )
  ))
```
